name: Run R Script Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup R environment
    - name: Setup R
      uses: r-lib/actions/setup-r@v2

    # Step 3: Install necessary packages
    - name: Install R packages
      run: |
        Rscript -e 'install.packages("perplexR")' # Add any required packages here
        Rscript -e 'install.packages("groqR")' # Add any required packages here
